import type { WordPair } from "../game/types";

export const wordPairs: WordPair[] = [
  { id: "france-italy", category: "countries", civilian: "France", undercover: "Italy" },
  { id: "stalin-mussolini", category: "history", civilian: "Stalin", undercover: "Mussolini" },
  { id: "dildo-toothbrush", category: "objects", civilian: "Dildo", undercover: "Toothbrush" },
  { id: "las-vegas-monaco", category: "places", civilian: "Las Vegas", undercover: "Monaco" },
  { id: "tax-evasion-offshore-account", category: "money", civilian: "Tax evasion", undercover: "Offshore account" },
  { id: "cult-yoga-retreat", category: "weird groups", civilian: "Cult", undercover: "Yoga retreat" },
  { id: "karaoke-interrogation", category: "nightlife", civilian: "Karaoke", undercover: "Interrogation" },
  { id: "strip-club-opera", category: "venues", civilian: "Strip club", undercover: "Opera" },
  { id: "nft-pyramid-scheme", category: "internet", civilian: "NFT", undercover: "Pyramid scheme" },
  { id: "cocaine-espresso", category: "substances", civilian: "Cocaine", undercover: "Espresso" },
  { id: "guillotine-air-fryer", category: "machines", civilian: "Guillotine", undercover: "Air fryer" },
  { id: "mona-lisa-onlyfans", category: "culture", civilian: "Mona Lisa", undercover: "OnlyFans" },
  { id: "vatican-disneyland", category: "places", civilian: "Vatican", undercover: "Disneyland" },
  { id: "bitcoin-casino-chip", category: "money", civilian: "Bitcoin", undercover: "Casino chip" },
  { id: "mafia-startup", category: "organizations", civilian: "Mafia", undercover: "Startup" },
  { id: "therapy-confession", category: "rituals", civilian: "Therapy", undercover: "Confession" },
  { id: "divorce-bachelor-party", category: "relationships", civilian: "Divorce", undercover: "Bachelor party" },
  { id: "absinthe-mouthwash", category: "liquids", civilian: "Absinthe", undercover: "Mouthwash" },
  { id: "rolex-ankle-monitor", category: "wearables", civilian: "Rolex", undercover: "Ankle monitor" },
  { id: "dictator-ceo", category: "power", civilian: "Dictator", undercover: "CEO" },
  { id: "prison-boarding-school", category: "institutions", civilian: "Prison", undercover: "Boarding school" },
  { id: "paparazzi-drone", category: "surveillance", civilian: "Paparazzi", undercover: "Drone" },
  { id: "blackmail-performance-review", category: "office", civilian: "Blackmail", undercover: "Performance review" },
  { id: "tinder-job-interview", category: "social", civilian: "Tinder", undercover: "Job interview" },
  { id: "plastic-surgery-photoshop", category: "beauty", civilian: "Plastic surgery", undercover: "Photoshop" },
  { id: "flamethrower-hairdryer", category: "objects", civilian: "Flamethrower", undercover: "Hairdryer" },
  { id: "moscow-dubai", category: "cities", civilian: "Moscow", undercover: "Dubai" },
  { id: "napoleon-putin", category: "leaders", civilian: "Napoleon", undercover: "Putin" },
  { id: "champagne-holy-water", category: "liquids", civilian: "Champagne", undercover: "Holy water" },
  { id: "caviar-instant-noodles", category: "food", civilian: "Caviar", undercover: "Instant noodles" },
  { id: "private-jet-uber", category: "transport", civilian: "Private jet", undercover: "Uber" },
  { id: "zombie-influencer", category: "characters", civilian: "Zombie", undercover: "Influencer" },
  { id: "meme-propaganda", category: "media", civilian: "Meme", undercover: "Propaganda" },
  { id: "conspiracy-theory-weather-forecast", category: "beliefs", civilian: "Conspiracy theory", undercover: "Weather forecast" },
  { id: "sauna-panic-room", category: "rooms", civilian: "Sauna", undercover: "Panic room" },
  { id: "hostage-intern", category: "jobs", civilian: "Hostage", undercover: "Intern" },
  { id: "casino-stock-market", category: "risk", civilian: "Casino", undercover: "Stock market" },
  { id: "tesla-hearse", category: "vehicles", civilian: "Tesla", undercover: "Hearse" },
  { id: "gossip-wikileaks", category: "secrets", civilian: "Gossip", undercover: "WikiLeaks" },
  { id: "botox-superglue", category: "chemicals", civilian: "Botox", undercover: "Superglue" },
  { id: "funeral-fashion-show", category: "events", civilian: "Funeral", undercover: "Fashion show" },
  { id: "satan-santa", category: "myths", civilian: "Satan", undercover: "Santa" },
  { id: "vodka-hand-sanitizer", category: "liquids", civilian: "Vodka", undercover: "Hand sanitizer" },
  { id: "missile-firework", category: "explosives", civilian: "Missile", undercover: "Firework" },
  { id: "lottery-ransom", category: "money", civilian: "Lottery", undercover: "Ransom" },
  { id: "luxury-bunker-wine-cellar", category: "rooms", civilian: "Luxury bunker", undercover: "Wine cellar" },
  { id: "politician-magician", category: "performers", civilian: "Politician", undercover: "Magician" },
  { id: "spy-therapist", category: "jobs", civilian: "Spy", undercover: "Therapist" },
  { id: "tesla-cybertruck-refrigerator", category: "objects", civilian: "Cybertruck", undercover: "Refrigerator" },
  { id: "hangover-enlightenment", category: "states", civilian: "Hangover", undercover: "Enlightenment" },
  { id: "napalm-sunscreen", category: "chemicals", civilian: "Napalm", undercover: "Sunscreen" },
  { id: "kidnapping-surprise-party", category: "events", civilian: "Kidnapping", undercover: "Surprise party" },
  { id: "tabloid-autopsy", category: "documents", civilian: "Tabloid", undercover: "Autopsy" },
  { id: "crown-traffic-cone", category: "headwear", civilian: "Crown", undercover: "Traffic cone" },
  { id: "louvre-ikea", category: "places", civilian: "Louvre", undercover: "IKEA" },
  { id: "bitcoin-miner-gold-digger", category: "people", civilian: "Bitcoin miner", undercover: "Gold digger" },
  { id: "escape-room-family-dinner", category: "activities", civilian: "Escape room", undercover: "Family dinner" },
  { id: "red-carpet-crime-scene", category: "places", civilian: "Red carpet", undercover: "Crime scene" },
  { id: "astrology-insider-trading", category: "prediction", civilian: "Astrology", undercover: "Insider trading" },
  { id: "tequila-truth-serum", category: "liquids", civilian: "Tequila", undercover: "Truth serum" },
  { id: "sugar-daddy-venture-capitalist", category: "money", civilian: "Sugar daddy", undercover: "Venture capitalist" },
  { id: "sex-dungeon-wine-cellar", category: "rooms", civilian: "Sex dungeon", undercover: "Wine cellar" },
  { id: "dark-web-flea-market", category: "commerce", civilian: "Dark web", undercover: "Flea market" },
  { id: "bribe-tip", category: "money", civilian: "Bribe", undercover: "Tip" },
  { id: "yacht-motel", category: "places", civilian: "Yacht", undercover: "Motel" },
  { id: "cougar-real-estate-agent", category: "people", civilian: "Cougar", undercover: "Real estate agent" },
  { id: "swingers-club-book-club", category: "social", civilian: "Swingers club", undercover: "Book club" },
  { id: "blood-diamond-engagement-ring", category: "jewelry", civilian: "Blood diamond", undercover: "Engagement ring" },
  { id: "tax-haven-spa-retreat", category: "places", civilian: "Tax haven", undercover: "Spa retreat" },
  { id: "burner-phone-bouquet", category: "objects", civilian: "Burner phone", undercover: "Bouquet" },
  { id: "black-card-library-card", category: "cards", civilian: "Black card", undercover: "Library card" },
  { id: "revenge-body-gym-membership", category: "beauty", civilian: "Revenge body", undercover: "Gym membership" },
  { id: "paternity-test-lottery-ticket", category: "documents", civilian: "Paternity test", undercover: "Lottery ticket" },
  { id: "ghosting-witness-protection", category: "disappearing", civilian: "Ghosting", undercover: "Witness protection" },
  { id: "midlife-crisis-space-mission", category: "states", civilian: "Midlife crisis", undercover: "Space mission" },
  { id: "dominatrix-life-coach", category: "jobs", civilian: "Dominatrix", undercover: "Life coach" },
  { id: "champagne-room-boardroom", category: "rooms", civilian: "Champagne room", undercover: "Boardroom" },
  { id: "speed-dating-auction", category: "events", civilian: "Speed dating", undercover: "Auction" },
  { id: "bail-money-wedding-budget", category: "money", civilian: "Bail money", undercover: "Wedding budget" },
  { id: "alibi-resume", category: "documents", civilian: "Alibi", undercover: "Resume" },
  { id: "hitman-consultant", category: "jobs", civilian: "Hitman", undercover: "Consultant" },
  { id: "scandal-podcast", category: "media", civilian: "Scandal", undercover: "Podcast" },
  { id: "peep-show-ted-talk", category: "performances", civilian: "Peep show", undercover: "TED Talk" },
  { id: "fake-passport-vip-pass", category: "documents", civilian: "Fake passport", undercover: "VIP pass" },
  { id: "hangover-spiritual-awakening", category: "states", civilian: "Hangover", undercover: "Spiritual awakening" },
  { id: "panic-attack-hot-yoga", category: "states", civilian: "Panic attack", undercover: "Hot yoga" },
  { id: "cocaine-breath-mint", category: "substances", civilian: "Cocaine", undercover: "Breath mint" },
  { id: "private-island-parking-spot", category: "property", civilian: "Private island", undercover: "Parking spot" },
  { id: "trophy-wife-mannequin", category: "people", civilian: "Trophy wife", undercover: "Mannequin" },
  { id: "walk-of-shame-parade", category: "events", civilian: "Walk of shame", undercover: "Parade" },
  { id: "polygraph-horoscope", category: "truth", civilian: "Polygraph", undercover: "Horoscope" },
  { id: "trust-fund-piggy-bank", category: "money", civilian: "Trust fund", undercover: "Piggy bank" },
  { id: "courtroom-group-chat", category: "social", civilian: "Courtroom", undercover: "Group chat" },
  { id: "affair-team-building", category: "relationships", civilian: "Affair", undercover: "Team building" },
  { id: "burlesque-powerpoint", category: "performances", civilian: "Burlesque", undercover: "PowerPoint" },
  { id: "safe-word-wifi-password", category: "phrases", civilian: "Safe word", undercover: "Wi-Fi password" },
  { id: "inheritance-loot-box", category: "money", civilian: "Inheritance", undercover: "Loot box" },
  { id: "telenovela-senate-hearing", category: "drama", civilian: "Telenovela", undercover: "Senate hearing" },
  { id: "botched-heist-office-party", category: "events", civilian: "Botched heist", undercover: "Office party" },
  { id: "cosmetic-filler-concrete", category: "chemicals", civilian: "Cosmetic filler", undercover: "Concrete" },
  { id: "casino-buffet-diplomatic-summit", category: "events", civilian: "Casino buffet", undercover: "Diplomatic summit" },
  { id: "luxury-prison-country-club", category: "places", civilian: "Luxury prison", undercover: "Country club" },
  { id: "revenge-plot-business-plan", category: "documents", civilian: "Revenge plot", undercover: "Business plan" },
  { id: "kink-contract-rental-agreement", category: "documents", civilian: "Kink contract", undercover: "Rental agreement" },
  { id: "hotline-ouija-board", category: "communication", civilian: "Hotline", undercover: "Ouija board" },
  { id: "saint-scammer", category: "characters", civilian: "Saint", undercover: "Scammer" },
  { id: "taboo-dinner-topic-board-game", category: "games", civilian: "Taboo dinner topic", undercover: "Board game" },
  { id: "designer-drug-perfume", category: "substances", civilian: "Designer drug", undercover: "Perfume" },
  { id: "red-flag-love-letter", category: "relationships", civilian: "Red flag", undercover: "Love letter" },
  { id: "offshore-shell-company-seashell", category: "money", civilian: "Shell company", undercover: "Seashell" },
  { id: "rage-room-couples-therapy", category: "activities", civilian: "Rage room", undercover: "Couples therapy" },
  { id: "paparazzi-family-album", category: "photos", civilian: "Paparazzi", undercover: "Family album" },
  { id: "royal-scandal-bachelorette-party", category: "events", civilian: "Royal scandal", undercover: "Bachelorette party" },
  { id: "startup-exit-prison-break", category: "escape", civilian: "Startup exit", undercover: "Prison break" },
  { id: "forbidden-fruit-energy-drink", category: "food", civilian: "Forbidden fruit", undercover: "Energy drink" },
  { id: "black-tie-interrogation", category: "events", civilian: "Black tie", undercover: "Interrogation" },
  { id: "sugar-rush-insider-trading", category: "risk", civilian: "Sugar rush", undercover: "Insider trading" },
  { id: "exorcism-performance-review", category: "rituals", civilian: "Exorcism", undercover: "Performance review" },
  { id: "velvet-rope-border-control", category: "security", civilian: "Velvet rope", undercover: "Border control" },
  { id: "gold-plated-toilet-throne", category: "objects", civilian: "Gold-plated toilet", undercover: "Throne" },
];
