import type { WordPair } from "../game/types";

const caesarShift = 7;

const encryptedWordPairs: WordPair[] = [
  { id: "myhujl-pahsf", category: "jvbuayplz", civilian: "Myhujl", undercover: "Pahsf" },
  { id: "zahspu-tbzzvspup", category: "opzavyf", civilian: "Zahspu", undercover: "Tbzzvspup" },
  { id: "kpskv-avvaoiybzo", category: "viqljaz", civilian: "Kpskv", undercover: "Avvaoiybzo" },
  { id: "shz-clnhz-tvuhjv", category: "wshjlz", civilian: "Shz Clnhz", undercover: "Tvuhjv" },
  { id: "ahe-lchzpvu-vmmzovyl-hjjvbua", category: "tvulf", civilian: "Ahe lchzpvu", undercover: "Vmmzovyl hjjvbua" },
  { id: "jbsa-fvnh-ylaylha", category: "dlpyk nyvbwz", civilian: "Jbsa", undercover: "Fvnh ylaylha" },
  { id: "rhyhvrl-vwlu-tpj-upnoa", category: "upnoaspml", civilian: "Rhyhvrl", undercover: "Vwlu tpj upnoa" },
  { id: "zaypw-jsbi-jhihyla", category: "clublz", civilian: "Zaypw jsbi", undercover: "Jhihyla" },
  { id: "uma-wfyhtpk-zjoltl", category: "pualyula", civilian: "UMA", undercover: "Wfyhtpk zjoltl" },
  { id: "jvjhpul-lzwylzzv", category: "zbizahujlz", civilian: "Jvjhpul", undercover: "Lzwylzzv" },
  { id: "nbpssvapul-lsljaypj-johpy", category: "thjopulz", civilian: "Nbpssvapul", undercover: "Lsljaypj johpy" },
  { id: "tvuh-spzh-aol-zjylht", category: "jbsabyl", civilian: "Tvuh Spzh", undercover: "Aol Zjylht" },
  { id: "chapjhu-tljjh", category: "wshjlz", civilian: "Chapjhu", undercover: "Tljjh" },
  { id: "ipajvpu-jhzpuv-jopw", category: "tvulf", civilian: "Ipajvpu", undercover: "Jhzpuv jopw" },
  { id: "thmph-jhyals", category: "vynhupghapvuz", civilian: "Thmph", undercover: "Jhyals" },
  { id: "aolyhwf-jvumlzzpvu", category: "ypabhsz", civilian: "Aolyhwf", undercover: "Jvumlzzpvu" },
  { id: "kpcvyjl-dlkkpun", category: "ylshapvuzopwz", civilian: "Kpcvyjl", undercover: "Dlkkpun" },
  { id: "hizpuaol-tvbaodhzo", category: "spxbpkz", civilian: "Hizpuaol", undercover: "Tvbaodhzo" },
  { id: "yvsle-hursl-tvupavy", category: "dlhyhislz", civilian: "Yvsle", undercover: "Hursl tvupavy" },
  { id: "kpjahavy-jlv", category: "wvdly", civilian: "Kpjahavy", undercover: "JLV" },
  { id: "wypzvu-ivhykpun-zjovvs", category: "puzapabapvuz", civilian: "Wypzvu", undercover: "Ivhykpun zjovvs" },
  { id: "whwhyhggp-kyvul", category: "zbyclpsshujl", civilian: "Whwhyhggp", undercover: "Kyvul" },
  { id: "ishjrthps-iypil", category: "vmmpjl", civilian: "Ishjrthps", undercover: "Iypil" },
  { id: "apukly-qvi-pualycpld", category: "zvjphs", civilian: "Apukly", undercover: "Qvi pualycpld" },
  { id: "wshzapj-zbynlyf-wovavzovw", category: "ilhbaf", civilian: "Wshzapj zbynlyf", undercover: "Wovavzovw" },
  { id: "mshtlaoyvdly-isvdavyjo", category: "viqljaz", civilian: "Mshtlaoyvdly", undercover: "Isvdavyjo" },
  { id: "tvzjvd-kbihp", category: "jpaplz", civilian: "Tvzjvd", undercover: "Kbihp" },
  { id: "uhwvslvu-wbapu", category: "slhklyz", civilian: "Uhwvslvu", undercover: "Wbapu" },
  { id: "johtwhnul-wyvzljjv", category: "spxbpkz", civilian: "Johtwhnul", undercover: "Wyvzljjv" },
  { id: "jhcphy-aybmmsl", category: "mvvk", civilian: "Jhcphy", undercover: "Aybmmsl" },
  { id: "wypchal-qla-bily", category: "ayhuzwvya", civilian: "Wypchal qla", undercover: "Bily" },
  { id: "gvtipl-chtwpyl", category: "johyhjalyz", civilian: "Gvtipl", undercover: "Chtwpyl" },
  { id: "tltl-wyvwhnhukh", category: "tlkph", civilian: "Tltl", undercover: "Wyvwhnhukh" },
  { id: "jvuzwpyhjf-aolvyf-ovyvzjvwl", category: "ilsplmz", civilian: "Jvuzwpyhjf aolvyf", undercover: "Ovyvzjvwl" },
  { id: "zhbuh-zalht-yvvt", category: "yvvtz", civilian: "Zhbuh", undercover: "Zalht yvvt" },
  { id: "ovzahnl-pualyu", category: "qviz", civilian: "Ovzahnl", undercover: "Pualyu" },
  { id: "jhzpuv-zavjr-thyrla", category: "ypzr", civilian: "Jhzpuv", undercover: "Zavjr thyrla" },
  { id: "alzsh-olhyzl", category: "clopjslz", civilian: "Alzsh", undercover: "Olhyzl" },
  { id: "nvzzpw-dprpslhrz", category: "zljylaz", civilian: "Nvzzpw", undercover: "DprpSlhrz" },
  { id: "ivave-mpssly", category: "joltpjhsz", civilian: "Ivave", undercover: "Mpssly" },
  { id: "mbulyhs-dlkkpun", category: "lcluaz", civilian: "Mbulyhs", undercover: "Dlkkpun" },
  { id: "zhahu-zhuah", category: "tfaoz", civilian: "Zhahu", undercover: "Zhuah" },
  { id: "cvkrh-ohuk-zhupapgly", category: "spxbpkz", civilian: "Cvkrh", undercover: "Ohuk zhupapgly" },
  { id: "tpzzpsl-mpyldvyr", category: "lewsvzpclz", civilian: "Tpzzpsl", undercover: "Mpyldvyr" },
  { id: "svaalyf-puolypahujl", category: "tvulf", civilian: "Svaalyf", undercover: "Puolypahujl" },
  { id: "sbebyf-iburly-dpul-jlsshy", category: "yvvtz", civilian: "Sbebyf iburly", undercover: "Dpul jlsshy" },
  { id: "wvspapjphu-thnpjphu", category: "wlymvytlyz", civilian: "Wvspapjphu", undercover: "Thnpjphu" },
  { id: "zwf-aolyhwpza", category: "qviz", civilian: "Zwf", undercover: "Aolyhwpza" },
  { id: "jfilyaybjr-ylmypnlyhavy", category: "viqljaz", civilian: "Jfilyaybjr", undercover: "Ylmypnlyhavy" },
  { id: "ohunvcly-mvvk-jvth", category: "zahalz", civilian: "Ohunvcly", undercover: "Mvvk jvth" },
  { id: "uhwhst-spnoaly-msbpk", category: "joltpjhsz", civilian: "Uhwhst", undercover: "Spnoaly msbpk" },
  { id: "rpkuhwwpun-zbywypzl-whyaf", category: "lcluaz", civilian: "Rpkuhwwpun", undercover: "Zbywypzl whyaf" },
  { id: "ahisvpk-ovyvzjvwl", category: "kvjbtluaz", civilian: "Ahisvpk", undercover: "Ovyvzjvwl" },
  { id: "jyvdu-aphyh", category: "olhkdlhy", civilian: "Jyvdu", undercover: "Aphyh" },
  { id: "svbcyl-prlh", category: "wshjlz", civilian: "Svbcyl", undercover: "PRLH" },
  { id: "ipajvpu-tpuly-nvsk-kpnnly", category: "wlvwsl", civilian: "Ipajvpu tpuly", undercover: "Nvsk kpnnly" },
  { id: "lzjhwl-yvvt-mhtpsf-kpuuly", category: "hjapcpaplz", civilian: "Lzjhwl yvvt", undercover: "Mhtpsf kpuuly" },
  { id: "ylk-jhywla-jhadhsr", category: "wshjlz", civilian: "Ylk jhywla", undercover: "Jhadhsr" },
  { id: "hzayvsvnf-ahyva", category: "wylkpjapvu", civilian: "Hzayvsvnf", undercover: "Ahyva" },
  { id: "alxbpsh-aybao-zlybt", category: "spxbpkz", civilian: "Alxbpsh", undercover: "Aybao zlybt" },
  { id: "zbnhy-khkkf-cluabyl-jhwpahspza", category: "tvulf", civilian: "Zbnhy khkkf", undercover: "Cluabyl jhwpahspza" },
  { id: "zle-kbunlvu-dpul-jlsshy", category: "yvvtz", civilian: "Zle kbunlvu", undercover: "Dpul jlsshy" },
  { id: "khyr-dli-mslh-thyrla", category: "jvttlyjl", civilian: "Khyr dli", undercover: "Mslh thyrla" },
  { id: "iypil-apw", category: "tvulf", civilian: "Iypil", undercover: "Apw" },
  { id: "fhjoa-jybpzl-zopw", category: "wshjlz", civilian: "Fhjoa", undercover: "Jybpzl zopw" },
  { id: "jvbnhy-zbnhy-tvttf", category: "wlvwsl", civilian: "Jvbnhy", undercover: "Zbnhy tvttf" },
  { id: "zdpunlyz-jsbi-zaypw-jsbi", category: "zvjphs", civilian: "Zdpunlyz jsbi", undercover: "Zaypw jsbi" },
  { id: "isvvk-kphtvuk-lunhnltlua-ypun", category: "qldlsyf", civilian: "Isvvk kphtvuk", undercover: "Lunhnltlua ypun" },
  { id: "ahe-ohclu-vmmzovyl-hjjvbua", category: "wshjlz", civilian: "Ahe ohclu", undercover: "Vmmzovyl hjjvbua" },
  { id: "ibyuly-wovul-dpylahw", category: "viqljaz", civilian: "Ibyuly wovul", undercover: "Dpylahw" },
  { id: "ishjr-jhyk-wshapubt-jhyk", category: "jhykz", civilian: "Ishjr jhyk", undercover: "Wshapubt jhyk" },
  { id: "ylclunl-ivkf-nft-tltilyzopw", category: "ilhbaf", civilian: "Ylclunl ivkf", undercover: "Nft tltilyzopw" },
  { id: "whalyupaf-alza-kuh-alza", category: "kvjbtluaz", civilian: "Whalyupaf alza", undercover: "KUH alza" },
  { id: "novzapun-dpaulzz-wyvaljapvu", category: "kpzhwwlhypun", civilian: "Novzapun", undercover: "Dpaulzz wyvaljapvu" },
  { id: "tpkspml-jypzpz-xbhyaly-spml-jypzpz", category: "zahalz", civilian: "Tpkspml jypzpz", undercover: "Xbhyaly-spml jypzpz" },
  { id: "kvtpuhaype-spml-jvhjo", category: "qviz", civilian: "Kvtpuhaype", undercover: "Spml jvhjo" },
  { id: "johtwhnul-yvvt-cpw-svbunl", category: "yvvtz", civilian: "Johtwhnul yvvt", undercover: "CPW svbunl" },
  { id: "zwllk-khapun-ispuk-khal", category: "lcluaz", civilian: "Zwllk khapun", undercover: "Ispuk khal" },
  { id: "ihps-tvulf-yhuzvt", category: "tvulf", civilian: "Ihps tvulf", undercover: "Yhuzvt" },
  { id: "hspip-jvcly-zavyf", category: "kvjbtluaz", civilian: "Hspip", undercover: "Jvcly zavyf" },
  { id: "opathu-jvuzbsahua", category: "qviz", civilian: "Opathu", undercover: "Jvuzbsahua" },
  { id: "zjhukhs-lewvz", category: "tlkph", civilian: "Zjhukhs", undercover: "Lewvzé" },
  { id: "wllw-zovd-ibyslzxbl-zovd", category: "wlymvythujlz", civilian: "Wllw zovd", undercover: "Ibyslzxbl zovd" },
  { id: "mhrl-whzzwvya-mhrl-pk", category: "kvjbtluaz", civilian: "Mhrl whzzwvya", undercover: "Mhrl PK" },
  { id: "ohunvcly-mvvk-wvpzvupun", category: "zahalz", civilian: "Ohunvcly", undercover: "Mvvk wvpzvupun" },
  { id: "whupj-haahjr-hueplaf-haahjr", category: "zahalz", civilian: "Whupj haahjr", undercover: "Hueplaf haahjr" },
  { id: "jvjhpul-wvdklylk-zbnhy", category: "zbizahujlz", civilian: "Jvjhpul", undercover: "Wvdklylk zbnhy" },
  { id: "wypchal-pzshuk-ilhjo-cpssh", category: "wyvwlyaf", civilian: "Wypchal pzshuk", undercover: "Ilhjo cpssh" },
  { id: "ayvwof-dpml-thuulxbpu", category: "wlvwsl", civilian: "Ayvwof dpml", undercover: "Thuulxbpu" },
  { id: "dhsr-vm-zohtl-wlyw-dhsr", category: "lcluaz", civilian: "Dhsr vm zohtl", undercover: "Wlyw dhsr" },
  { id: "wvsfnyhwo-pualyyvnhapvu", category: "aybao", civilian: "Wvsfnyhwo", undercover: "Pualyyvnhapvu" },
  { id: "aybza-mbuk-wpnnf-ihur", category: "tvulf", civilian: "Aybza mbuk", undercover: "Wpnnf ihur" },
  { id: "jvbyayvvt-mhtpsf-kpuuly", category: "zvjphs", civilian: "Jvbyayvvt", undercover: "Mhtpsf kpuuly" },
  { id: "hmmhpy-vul-upnoa-zahuk", category: "ylshapvuzopwz", civilian: "Hmmhpy", undercover: "Vul-upnoa zahuk" },
  { id: "ibyslzxbl-zaypw-jsbi", category: "wlymvythujlz", civilian: "Ibyslzxbl", undercover: "Zaypw jsbi" },
  { id: "zhml-dvyk-zljyla-whzzdvyk", category: "woyhzlz", civilian: "Zhml dvyk", undercover: "Zljyla whzzdvyk" },
  { id: "puolypahujl-svaalyf-dpu", category: "tvulf", civilian: "Puolypahujl", undercover: "Svaalyf dpu" },
  { id: "alsluvclsh-ylhspaf-ac-zovd", category: "kyhth", civilian: "Alsluvclsh", undercover: "Ylhspaf AC zovd" },
  { id: "ivajolk-olpza-ihur-yviilyf", category: "lcluaz", civilian: "Ivajolk olpza", undercover: "Ihur yviilyf" },
  { id: "jvztlapj-mpssly-ivave", category: "joltpjhsz", civilian: "Jvztlapj mpssly", undercover: "Ivave" },
  { id: "jhzpuv-ibmmla-dlkkpun-yljlwapvu", category: "lcluaz", civilian: "Jhzpuv ibmmla", undercover: "Dlkkpun yljlwapvu" },
  { id: "sbebyf-wypzvu-jvbuayf-jsbi", category: "wshjlz", civilian: "Sbebyf wypzvu", undercover: "Jvbuayf jsbi" },
  { id: "ylclunl-wsva-ibzpulzz-wshu", category: "kvjbtluaz", civilian: "Ylclunl wsva", undercover: "Ibzpulzz wshu" },
  { id: "rpur-jvuayhja-yluahs-hnylltlua", category: "kvjbtluaz", civilian: "Rpur jvuayhja", undercover: "Yluahs hnylltlua" },
  { id: "ovaspul-z-hujl", category: "jvttbupjhapvu", civilian: "Ovaspul", undercover: "Zéhujl" },
  { id: "zhpua-thyafy", category: "johyhjalyz", civilian: "Zhpua", undercover: "Thyafy" },
  { id: "ahivv-kpuuly-avwpj-wvspapjz", category: "nhtlz", civilian: "Ahivv kpuuly avwpj", undercover: "Wvspapjz" },
  { id: "klzpnuly-kybn-ljzahzf", category: "zbizahujlz", civilian: "Klzpnuly kybn", undercover: "Ljzahzf" },
  { id: "ylk-mshn-nyllu-mshn", category: "ylshapvuzopwz", civilian: "Ylk mshn", undercover: "Nyllu mshn" },
  { id: "zolss-jvtwhuf-vmmzovyl-hjjvbua", category: "tvulf", civilian: "Zolss jvtwhuf", undercover: "Vmmzovyl hjjvbua" },
  { id: "yhnl-yvvt-ivepun-jshzz", category: "hjapcpaplz", civilian: "Yhnl yvvt", undercover: "Ivepun jshzz" },
  { id: "whwhyhggp-zlsmpl", category: "wovavz", civilian: "Whwhyhggp", undercover: "Zlsmpl" },
  { id: "yvfhs-zjhukhs-jlsliypaf-kpcvyjl", category: "lcluaz", civilian: "Yvfhs zjhukhs", undercover: "Jlsliypaf kpcvyjl" },
  { id: "zahyabw-lepa-wypzvu-iylhr", category: "lzjhwl", civilian: "Zahyabw lepa", undercover: "Wypzvu iylhr" },
  { id: "mvyipkklu-mybpa-jolha-tlhs", category: "mvvk", civilian: "Mvyipkklu mybpa", undercover: "Jolha tlhs" },
  { id: "ishjr-apl-ylk-jhywla", category: "lcluaz", civilian: "Ishjr apl", undercover: "Ylk jhywla" },
  { id: "zbnhy-ybzo-jhmmlpul-opno", category: "ypzr", civilian: "Zbnhy ybzo", undercover: "Jhmmlpul opno" },
  { id: "levyjpzt-ihwapzt", category: "ypabhsz", civilian: "Levyjpzt", undercover: "Ihwapzt" },
  { id: "clscla-yvwl-ivykly-jvuayvs", category: "zljbypaf", civilian: "Clscla yvwl", undercover: "Ivykly jvuayvs" },
  { id: "nvsk-wshalk-avpsla-aoyvul", category: "viqljaz", civilian: "Nvsk-wshalk avpsla", undercover: "Aoyvul" },
  { id: "yhiipa-ohyl", category: "hupthsz", civilian: "Yhiipa", undercover: "Ohyl" },
  { id: "slvwhyk-jollaho", category: "hupthsz", civilian: "Slvwhyk", undercover: "Jollaho" },
  { id: "kvswopu-dohsl", category: "hupthsz", civilian: "Kvswopu", undercover: "Dohsl" },
  { id: "lhnsl-ohdr", category: "hupthsz", civilian: "Lhnsl", undercover: "Ohdr" },
  { id: "abyasl-avyavpzl", category: "hupthsz", civilian: "Abyasl", undercover: "Avyavpzl" },
  { id: "ovyzl-kvurlf", category: "hupthsz", civilian: "Ovyzl", undercover: "Kvurlf" },
  { id: "ill-dhzw", category: "hupthsz", civilian: "Ill", undercover: "Dhzw" },
  { id: "zuhps-zsbn", category: "hupthsz", civilian: "Zuhps", undercover: "Zsbn" },
  { id: "nvha-zollw", category: "hupthsz", civilian: "Nvha", undercover: "Zollw" },
  { id: "wlunbpu-zlhs", category: "hupthsz", civilian: "Wlunbpu", undercover: "Zlhs" },
  { id: "zlh-vjlhu", category: "uhabyl", civilian: "Zlh", undercover: "Vjlhu" },
  { id: "ypcly-zaylht", category: "uhabyl", civilian: "Ypcly", undercover: "Zaylht" },
  { id: "tvbuahpu-opss", category: "uhabyl", civilian: "Tvbuahpu", undercover: "Opss" },
  { id: "yhpu-zuvd", category: "uhabyl", civilian: "Yhpu", undercover: "Zuvd" },
  { id: "jsvbk-mvn", category: "uhabyl", civilian: "Jsvbk", undercover: "Mvn" },
  { id: "mvylza-qbunsl", category: "uhabyl", civilian: "Mvylza", undercover: "Qbunsl" },
  { id: "yvzl-abspw", category: "uhabyl", civilian: "Yvzl", undercover: "Abspw" },
  { id: "zwpkly-zjvywpvu", category: "uhabyl", civilian: "Zwpkly", undercover: "Zjvywpvu" },
  { id: "zhstvu-ayvba", category: "hupthsz", civilian: "Zhstvu", undercover: "Ayvba" },
  { id: "vds-iha", category: "hupthsz", civilian: "Vds", undercover: "Iha" },
  { id: "jvmmll-alh", category: "kypurz", civilian: "Jvmmll", undercover: "Alh" },
  { id: "sltvu-sptl", category: "mybpaz", civilian: "Sltvu", undercover: "Sptl" },
  { id: "zayhdilyyf-yhzwilyyf", category: "mybpaz", civilian: "Zayhdilyyf", undercover: "Yhzwilyyf" },
  { id: "wpggh-shzhnuh", category: "kpzolz", civilian: "Wpggh", undercover: "Shzhnuh" },
  { id: "ibynly-zhukdpjo", category: "kpzolz", civilian: "Ibynly", undercover: "Zhukdpjo" },
  { id: "jhrl-wpl", category: "zdllaz", civilian: "Jhrl", undercover: "Wpl" },
  { id: "pjl-jylht-zvyila", category: "zdllaz", civilian: "Pjl jylht", undercover: "Zvyila" },
  { id: "illy-jpkly", category: "kypurz", civilian: "Illy", undercover: "Jpkly" },
  { id: "whujhrl-dhmmsl", category: "iylhrmhza", civilian: "Whujhrl", undercover: "Dhmmsl" },
  { id: "jhyyva-wvahav", category: "clnlahislz", civilian: "Jhyyva", undercover: "Wvahav" },
  { id: "zvbw-zald", category: "kpzolz", civilian: "Zvbw", undercover: "Zald" },
  { id: "jovjvshal-jhyhtls", category: "zdllaz", civilian: "Jovjvshal", undercover: "Jhyhtls" },
  { id: "zwhnolaap-uvvkslz", category: "whzah", civilian: "Zwhnolaap", undercover: "Uvvkslz" },
  { id: "tpsr-fvnbya", category: "kypurz", civilian: "Tpsr", undercover: "Fvnbya" },
  { id: "jbjbtily-gbjjopup", category: "clnlahislz", civilian: "Jbjbtily", undercover: "Gbjjopup" },
  { id: "qht-ovulf", category: "iylhrmhza", civilian: "Qht", undercover: "Ovulf" },
  { id: "nyhwl-jolyyf", category: "mybpaz", civilian: "Nyhwl", undercover: "Jolyyf" },
  { id: "ztvvaopl-tpsrzohrl", category: "kypurz", civilian: "Ztvvaopl", undercover: "Tpsrzohrl" },
  { id: "ahjv-ibyypav", category: "kpzolz", civilian: "Ahjv", undercover: "Ibyypav" },
  { id: "kvuba-ihnls", category: "zdllaz", civilian: "Kvuba", undercover: "Ihnls" },
  { id: "mypknl-myllgly", category: "viqljaz", civilian: "Mypknl", undercover: "Myllgly" },
  { id: "tpjyvdhcl-vclu", category: "viqljaz", civilian: "Tpjyvdhcl", undercover: "Vclu" },
  { id: "rlaasl-alhwva", category: "viqljaz", civilian: "Rlaasl", undercover: "Alhwva" },
  { id: "avhzaly-islukly", category: "viqljaz", civilian: "Avhzaly", undercover: "Islukly" },
  { id: "whu-wva", category: "viqljaz", civilian: "Whu", undercover: "Wva" },
  { id: "chjbbt-jslhuly-iyvvt", category: "viqljaz", civilian: "Chjbbt jslhuly", undercover: "Iyvvt" },
  { id: "zavvs-johpy", category: "viqljaz", civilian: "Zavvs", undercover: "Johpy" },
  { id: "kyhdly-jbwivhyk", category: "viqljaz", civilian: "Kyhdly", undercover: "Jbwivhyk" },
  { id: "tpyyvy-dpukvd", category: "viqljaz", civilian: "Tpyyvy", undercover: "Dpukvd" },
  { id: "jbyahpu-ispuk", category: "viqljaz", civilian: "Jbyahpu", undercover: "Ispuk" },
  { id: "kypss-zhd", category: "viqljaz", civilian: "Kypss", undercover: "Zhd" },
  { id: "uhps-zjyld", category: "viqljaz", civilian: "Uhps", undercover: "Zjyld" },
  { id: "dylujo-wsplyz", category: "viqljaz", civilian: "Dylujo", undercover: "Wsplyz" },
  { id: "johynly-ihaalyf", category: "viqljaz", civilian: "Johynly", undercover: "Ihaalyf" },
  { id: "olhkwovulz-zwlhrly", category: "viqljaz", civilian: "Olhkwovulz", undercover: "Zwlhrly" },
  { id: "rlfivhyk-tvbzl", category: "viqljaz", civilian: "Rlfivhyk", undercover: "Tvbzl" },
  { id: "mhu-hpy-jvukpapvuly", category: "viqljaz", civilian: "Mhu", undercover: "Hpy jvukpapvuly" },
  { id: "ihjrwhjr-zbpajhzl", category: "viqljaz", civilian: "Ihjrwhjr", undercover: "Zbpajhzl" },
  { id: "btiylssh-yhpujvha", category: "viqljaz", civilian: "Btiylssh", undercover: "Yhpujvha" },
  { id: "thnula-zapjrly", category: "viqljaz", civilian: "Thnula", undercover: "Zapjrly" },
  { id: "zbidhf-ayht", category: "ayhuzwvya", civilian: "Zbidhf", undercover: "Ayht" },
  { id: "ahep-sptvbzpul", category: "ayhuzwvya", civilian: "Ahep", undercover: "Sptvbzpul" },
  { id: "ipjfjsl-zjvvaly", category: "ayhuzwvya", civilian: "Ipjfjsl", undercover: "Zjvvaly" },
  { id: "mlyyf-jybpzl-zopw", category: "ayhuzwvya", civilian: "Mlyyf", undercover: "Jybpzl zopw" },
  { id: "aybjr-chu", category: "ayhuzwvya", civilian: "Aybjr", undercover: "Chu" },
  { id: "ovzwpahs-wohythjf", category: "wshjlz", civilian: "Ovzwpahs", undercover: "Wohythjf" },
  { id: "tbzlbt-nhsslyf", category: "wshjlz", civilian: "Tbzlbt", undercover: "Nhsslyf" },
  { id: "jobyjo-tvzxbl", category: "wshjlz", civilian: "Jobyjo", undercover: "Tvzxbl" },
  { id: "zbwlythyrla-thyrla", category: "wshjlz", civilian: "Zbwlythyrla", undercover: "Thyrla" },
  { id: "zahkpbt-hyluh", category: "wshjlz", civilian: "Zahkpbt", undercover: "Hyluh" },
  { id: "ihrlyf-ibajoly", category: "wshjlz", civilian: "Ihrlyf", undercover: "Ibajoly" },
  { id: "gvv-hxbhypbt", category: "wshjlz", civilian: "Gvv", undercover: "Hxbhypbt" },
  { id: "shrl-wvuk", category: "wshjlz", civilian: "Shrl", undercover: "Wvuk" },
  { id: "mhyt-yhujo", category: "wshjlz", civilian: "Mhyt", undercover: "Yhujo" },
  { id: "rpajolu-ihaoyvvt", category: "yvvtz", civilian: "Rpajolu", undercover: "Ihaoyvvt" },
  { id: "ilkyvvt-haapj", category: "yvvtz", civilian: "Ilkyvvt", undercover: "Haapj" },
  { id: "nhyhnl-zolk", category: "wshjlz", civilian: "Nhyhnl", undercover: "Zolk" },
  { id: "ihur-wvza-vmmpjl", category: "wshjlz", civilian: "Ihur", undercover: "Wvza vmmpjl" },
  { id: "alua-jhipu", category: "ayhcls", civilian: "Alua", undercover: "Jhipu" },
  { id: "jhzasl-whshjl", category: "wshjlz", civilian: "Jhzasl", undercover: "Whshjl" },
  { id: "kvjavy-kluapza", category: "qviz", civilian: "Kvjavy", undercover: "Kluapza" },
  { id: "mpylmpnoaly-wvspjl-vmmpjly", category: "qviz", civilian: "Mpylmpnoaly", undercover: "Wvspjl vmmpjly" },
  { id: "jolm-ihrly", category: "qviz", civilian: "Jolm", undercover: "Ihrly" },
  { id: "wpsva-hzayvuhba", category: "qviz", civilian: "Wpsva", undercover: "Hzayvuhba" },
  { id: "alhjoly-spiyhyphu", category: "qviz", civilian: "Alhjoly", undercover: "Spiyhyphu" },
  { id: "mhytly-nhykluly", category: "qviz", civilian: "Mhytly", undercover: "Nhykluly" },
  { id: "shdfly-qbknl", category: "qviz", civilian: "Shdfly", undercover: "Qbknl" },
  { id: "mvvaihss-ybnif", category: "zwvyaz", civilian: "Mvvaihss", undercover: "Ybnif" },
  { id: "aluupz-ihktpuavu", category: "zwvyaz", civilian: "Aluupz", undercover: "Ihktpuavu" },
  { id: "ivepun-dylzaspun", category: "zwvyaz", civilian: "Ivepun", undercover: "Dylzaspun" },
  { id: "zdpttpun-kpcpun", category: "zwvyaz", civilian: "Zdpttpun", undercover: "Kpcpun" },
  { id: "ihzrlaihss-cvsslfihss", category: "zwvyaz", civilian: "Ihzrlaihss", undercover: "Cvsslfihss" },
  { id: "zrppun-zuvdivhykpun", category: "zwvyaz", civilian: "Zrppun", undercover: "Zuvdivhykpun" },
  { id: "nbpahy-cpvspu", category: "tbzpj", civilian: "Nbpahy", undercover: "Cpvspu" },
  { id: "wphuv-vynhu", category: "tbzpj", civilian: "Wphuv", undercover: "Vynhu" },
  { id: "aybtwla-ayvtivul", category: "tbzpj", civilian: "Aybtwla", undercover: "Ayvtivul" },
  { id: "msbal-jshypula", category: "tbzpj", civilian: "Msbal", undercover: "Jshypula" },
  { id: "whpuapun-kyhdpun", category: "oviiplz", civilian: "Whpuapun", undercover: "Kyhdpun" },
  { id: "wovavnyhwof-mpstthrpun", category: "oviiplz", civilian: "Wovavnyhwof", undercover: "Mpstthrpun" },
  { id: "thnpjphu-jsvdu", category: "wlymvytlyz", civilian: "Thnpjphu", undercover: "Jsvdu" },
];

export const wordPairs: WordPair[] = encryptedWordPairs.map(decryptWordPair);

function decryptWordPair(pair: WordPair): WordPair {
  return {
    id: decrypt(pair.id),
    category: decrypt(pair.category),
    civilian: decrypt(pair.civilian),
    undercover: decrypt(pair.undercover),
  };
}

function decrypt(value: string): string {
  return value.replace(/[a-z]/gi, (letter) => shiftLetter(letter, -caesarShift));
}

function shiftLetter(letter: string, shift: number): string {
  const alphabetStart = letter >= "a" && letter <= "z" ? 97 : 65;
  const alphabetSize = 26;
  const charOffset = letter.charCodeAt(0) - alphabetStart;
  const shiftedOffset = (charOffset + shift + alphabetSize) % alphabetSize;

  return String.fromCharCode(alphabetStart + shiftedOffset);
}
