import type { WordPair } from "../game/types";

export const wordPairs: WordPair[] = [
  { id: "france-italy", category: "countries", civilian: "France", undercover: "Italy" },
  { id: "stalin-mussolini", category: "history", civilian: "Stalin", undercover: "Mussolini" },
  { id: "dildo-toothbrush", category: "objects", civilian: "Dildo", undercover: "Toothbrush" },
  { id: "las-vegas-monaco", category: "places", civilian: "Las Vegas", undercover: "Monaco" },
  { id: "tax-evasion-offshore-account", category: "money", civilian: "Tax evasion", undercover: "Offshore account" },
  { id: "cult-yoga-retreat", category: "weird groups", civilian: "Cult", undercover: "Yoga retreat" },
  { id: "karaoke-interrogation", category: "nightlife", civilian: "Karaoke", undercover: "Interrogation" },
  { id: "strip-club-opera", category: "venues", civilian: "Strip club", undercover: "Opera" },
  { id: "nft-pyramid-scheme", category: "internet", civilian: "NFT", undercover: "Pyramid scheme" },
  { id: "cocaine-espresso", category: "substances", civilian: "Cocaine", undercover: "Espresso" },
  { id: "guillotine-air-fryer", category: "machines", civilian: "Guillotine", undercover: "Air fryer" },
  { id: "mona-lisa-onlyfans", category: "culture", civilian: "Mona Lisa", undercover: "OnlyFans" },
  { id: "vatican-disneyland", category: "places", civilian: "Vatican", undercover: "Disneyland" },
  { id: "bitcoin-casino-chip", category: "money", civilian: "Bitcoin", undercover: "Casino chip" },
  { id: "mafia-startup", category: "organizations", civilian: "Mafia", undercover: "Startup" },
  { id: "therapy-confession", category: "rituals", civilian: "Therapy", undercover: "Confession" },
  { id: "divorce-bachelor-party", category: "relationships", civilian: "Divorce", undercover: "Bachelor party" },
  { id: "absinthe-mouthwash", category: "liquids", civilian: "Absinthe", undercover: "Mouthwash" },
  { id: "rolex-ankle-monitor", category: "wearables", civilian: "Rolex", undercover: "Ankle monitor" },
  { id: "dictator-ceo", category: "power", civilian: "Dictator", undercover: "CEO" },
  { id: "prison-boarding-school", category: "institutions", civilian: "Prison", undercover: "Boarding school" },
  { id: "paparazzi-drone", category: "surveillance", civilian: "Paparazzi", undercover: "Drone" },
  { id: "blackmail-performance-review", category: "office", civilian: "Blackmail", undercover: "Performance review" },
  { id: "tinder-job-interview", category: "social", civilian: "Tinder", undercover: "Job interview" },
  { id: "plastic-surgery-photoshop", category: "beauty", civilian: "Plastic surgery", undercover: "Photoshop" },
  { id: "flamethrower-hairdryer", category: "objects", civilian: "Flamethrower", undercover: "Hairdryer" },
  { id: "moscow-dubai", category: "cities", civilian: "Moscow", undercover: "Dubai" },
  { id: "napoleon-putin", category: "leaders", civilian: "Napoleon", undercover: "Putin" },
  { id: "champagne-holy-water", category: "liquids", civilian: "Champagne", undercover: "Holy water" },
  { id: "caviar-instant-noodles", category: "food", civilian: "Caviar", undercover: "Instant noodles" },
  { id: "private-jet-uber", category: "transport", civilian: "Private jet", undercover: "Uber" },
  { id: "zombie-influencer", category: "characters", civilian: "Zombie", undercover: "Influencer" },
  { id: "meme-propaganda", category: "media", civilian: "Meme", undercover: "Propaganda" },
  { id: "conspiracy-theory-weather-forecast", category: "beliefs", civilian: "Conspiracy theory", undercover: "Weather forecast" },
  { id: "sauna-panic-room", category: "rooms", civilian: "Sauna", undercover: "Panic room" },
  { id: "hostage-intern", category: "jobs", civilian: "Hostage", undercover: "Intern" },
  { id: "casino-stock-market", category: "risk", civilian: "Casino", undercover: "Stock market" },
  { id: "tesla-hearse", category: "vehicles", civilian: "Tesla", undercover: "Hearse" },
  { id: "gossip-wikileaks", category: "secrets", civilian: "Gossip", undercover: "WikiLeaks" },
  { id: "botox-superglue", category: "chemicals", civilian: "Botox", undercover: "Superglue" },
  { id: "funeral-fashion-show", category: "events", civilian: "Funeral", undercover: "Fashion show" },
  { id: "satan-santa", category: "myths", civilian: "Satan", undercover: "Santa" },
  { id: "vodka-hand-sanitizer", category: "liquids", civilian: "Vodka", undercover: "Hand sanitizer" },
  { id: "missile-firework", category: "explosives", civilian: "Missile", undercover: "Firework" },
  { id: "lottery-ransom", category: "money", civilian: "Lottery", undercover: "Ransom" },
  { id: "luxury-bunker-wine-cellar", category: "rooms", civilian: "Luxury bunker", undercover: "Wine cellar" },
  { id: "politician-magician", category: "performers", civilian: "Politician", undercover: "Magician" },
  { id: "spy-therapist", category: "jobs", civilian: "Spy", undercover: "Therapist" },
  { id: "tesla-cybertruck-refrigerator", category: "objects", civilian: "Cybertruck", undercover: "Refrigerator" },
  { id: "hangover-enlightenment", category: "states", civilian: "Hangover", undercover: "Enlightenment" },
  { id: "napalm-sunscreen", category: "chemicals", civilian: "Napalm", undercover: "Sunscreen" },
  { id: "kidnapping-surprise-party", category: "events", civilian: "Kidnapping", undercover: "Surprise party" },
  { id: "tabloid-autopsy", category: "documents", civilian: "Tabloid", undercover: "Autopsy" },
  { id: "crown-traffic-cone", category: "headwear", civilian: "Crown", undercover: "Traffic cone" },
  { id: "louvre-ikea", category: "places", civilian: "Louvre", undercover: "IKEA" },
  { id: "bitcoin-miner-gold-digger", category: "people", civilian: "Bitcoin miner", undercover: "Gold digger" },
  { id: "escape-room-family-dinner", category: "activities", civilian: "Escape room", undercover: "Family dinner" },
  { id: "red-carpet-crime-scene", category: "places", civilian: "Red carpet", undercover: "Crime scene" },
  { id: "astrology-insider-trading", category: "prediction", civilian: "Astrology", undercover: "Insider trading" },
  { id: "tequila-truth-serum", category: "liquids", civilian: "Tequila", undercover: "Truth serum" },
];
